name: Build pull request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Building
        run: ./gradlew build -x test

      - name: Unit-testing
        run: ./gradlew test

      - name: Adding coverage to Pull-Request
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml,
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 60
          title: Code Coverage
          update-comment: true

  codecov:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: divinenickname/utgen-kotlin-core


